In [9]:
import os
import sys
import random
import warnings
import time

import numpy as np
import pandas as pd
import cv2

import matplotlib.pyplot as plt

from tqdm import tqdm
from itertools import chain
from skimage.io import imread, imshow, imread_collection, concatenate_images
from skimage.transform import resize
from skimage.morphology import label

from keras.models import Model, load_model
from keras.layers import Input
from keras.layers.core import Dropout, Lambda
from keras.layers.convolutional import Conv2D, Conv2DTranspose
from keras.layers.pooling import MaxPooling2D
from keras.layers.merge import concatenate
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras import backend as K

import tensorflow as tf

# Set some parameters
IMG_WIDTH = 256
IMG_HEIGHT = 256
IMG_CHANNELS = 3
TRAIN_PATH = 'G:/Kaggle_data/Kaggle_bowl/stage1_train/'
TEST_PATH = 'G:/Kaggle_data/Kaggle_bowl/stage1_test/'

warnings.filterwarnings('ignore', category=UserWarning, module='skimage')
seed = 42
random.seed = seed
np.random.seed = seed
time = time.strftime("%Y-%m-%d", time.gmtime())

smooth = 1

# Get train and test IDs
train_ids = next(os.walk(TRAIN_PATH))[1]
test_ids = next(os.walk(TEST_PATH))[1]

# Get and resize train images and masks
X_train = np.zeros((len(train_ids), IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), dtype=np.uint8)
Y_train = np.zeros((len(train_ids), IMG_HEIGHT, IMG_WIDTH, 1), dtype=np.bool)
print('Getting and resizing train images and masks ... ')
sys.stdout.flush()
for n, id_ in tqdm(enumerate(train_ids), total=len(train_ids)):
    path = TRAIN_PATH + id_
    img = imread(path + '/images/' + id_ + '.png')[:,:,:IMG_CHANNELS]
    img = resize(img, (IMG_HEIGHT, IMG_WIDTH), mode='constant', preserve_range=True)
    X_train[n] = img
    mask = np.zeros((IMG_HEIGHT, IMG_WIDTH, 1), dtype=np.bool)
    for mask_file in next(os.walk(path + '/masks/'))[2]:
        mask_ = imread(path + '/masks/' + mask_file)
        mask_ = np.expand_dims(resize(mask_, (IMG_HEIGHT, IMG_WIDTH), mode='constant', 
                                      preserve_range=True), axis=-1)
        mask = np.maximum(mask, mask_)
    Y_train[n] = mask
    
#def scale_img_canals(an_img):
for i in range(IMG_CHANNELS):
    canal = img[:,:,i]
    canal = canal - canal.min()
    canalmax = canal.max()
    if canalmax > 0:
        factor = 255/canalmax
        canal = (canal * factor).astype(int)
    img[:,:,i] = canal

# Get and resize test images
X_test = np.zeros((len(test_ids), IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS), dtype=np.uint8)
sizes_test = []
print('Getting and resizing test images ... ')
sys.stdout.flush()
for n, id_ in tqdm(enumerate(test_ids), total=len(test_ids)):
    path = TEST_PATH + id_
    img = imread(path + '/images/' + id_ + '.png')[:,:,:IMG_CHANNELS]
    sizes_test.append([img.shape[0], img.shape[1]])
    img = resize(img, (IMG_HEIGHT, IMG_WIDTH), mode='constant', preserve_range=True)
    X_test[n] = img
    
for i in range(IMG_CHANNELS):
    canal = img[:,:,i]
    canal = canal - canal.min()
    canalmax = canal.max()
    if canalmax > 0:
        factor = 255/canalmax
        canal = (canal * factor).astype(int)
    img[:,:,i] = canal

print('Done!')

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)

def get_more_images(imgs):
    
    more_images = []
    vert_flip_imgs = []
    hori_flip_imgs = []
    rotated_images_pos90 = []
    rotated_images_neg90 = []
    
    for i in range(0,imgs.shape[0]):
        a=imgs[i,:,:,0]
        b=imgs[i,:,:,1]
        c=imgs[i,:,:,2]
        
#         IMG_HEIGHT = imgs.shape[0]
#         IMG_WIDTH = imgs.shape[1]
    
        av=cv2.flip(a,1)
        ah=cv2.flip(a,0)
        bv=cv2.flip(b,1)
        bh=cv2.flip(b,0)
        cv=cv2.flip(c,1)
        ch=cv2.flip(c,0)
        
        arp90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),90,1)
        arp90_r = cv2.warpAffine(a,arp90,(IMG_WIDTH,IMG_HEIGHT))
        
        arn90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),270,1)
        arn90_r = cv2.warpAffine(a,arn90,(IMG_WIDTH,IMG_HEIGHT))
        
        brp90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),90,1)
        brp90_r = cv2.warpAffine(a,brp90,(IMG_WIDTH,IMG_HEIGHT))
        
        brn90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),270,1)
        brn90_r = cv2.warpAffine(a,brn90,(IMG_WIDTH,IMG_HEIGHT))
        
        crp90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),90,1)
        crp90_r = cv2.warpAffine(a,crp90,(IMG_WIDTH,IMG_HEIGHT))
        
        crn90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),270,1)
        crn90_r = cv2.warpAffine(a,crn90,(IMG_WIDTH,IMG_HEIGHT))
        
        vert_flip_imgs.append(np.dstack((av, bv, cv)))
        hori_flip_imgs.append(np.dstack((ah, bh, ch)))
        rotated_images_pos90.append(np.dstack((arp90_r, brp90_r, crp90_r)))
        rotated_images_neg90.append(np.dstack((arn90_r, brn90_r, crn90_r)))
    
    v = np.array(vert_flip_imgs)
    h = np.array(hori_flip_imgs)
    rp = np.array(rotated_images_pos90)
    rn = np.array(rotated_images_neg90)
    
    print(v)
#     print('h shape \n' + h)
    print(rp)
#     print('rn shape \n' + rn)
    more_images = np.concatenate((imgs,v,h,rp,rn))
    
    return more_images

def duplicate_labels(labels):
    more_images = []
    vert_flip_imgs = []
    hori_flip_imgs = []
    rotated_images_pos90 = []
    rotated_images_neg90 = []
    for i in range(0,labels.shape[0]):
        
#         IMG_HEIGHT = labels.shape[0]
#         IMG_WIDTH = labels.shape[1]
        
        a=labels[i,:,:,0]

        av=cv2.flip(a,1)
        ah=cv2.flip(a,0)
        
        arp90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),90,1)
        arp90_r = cv2.warpAffine(a,arp90,(IMG_WIDTH,IMG_HEIGHT))
        
        arn90=cv2.getRotationMatrix2D((IMG_WIDTH/2,IMG_HEIGHT/2),-90,1)
        arn90_r = cv2.warpAffine(a,arn90,(IMG_WIDTH,IMG_HEIGHT))
        
        vert_flip_imgs.append(av.reshape(IMG_WIDTH,IMG_WIDTH,1))
        hori_flip_imgs.append(ah.reshape(IMG_WIDTH,IMG_WIDTH,1))
        rotated_images_pos90.append(arp90_r.reshape(IMG_WIDTH,IMG_WIDTH,1))
        rotated_images_neg90.append(arn90_r.reshape(IMG_WIDTH,IMG_WIDTH,1))
        
    v = np.array(vert_flip_imgs)
    h = np.array(hori_flip_imgs)
    rp = np.array(rotated_images_pos90)
    rn = np.array(rotated_images_neg90)
    duplicate_labels = np.concatenate((labels,v,h,rp,rn))
    return duplicate_labels

X_validation = X_train[-50:,...]
Y_validation = Y_train[-50:]
X_train = X_train[0:-50,...]
Y_train = Y_train[0:-50]
print("Validation Set of Size "+str(Y_validation.shape[0])+" Separated")
Y_train.dtype = np.uint8
X_train = get_more_images(X_train)
Y_train = duplicate_labels(Y_train)
print (X_train.shape)
print (Y_train.shape)
print (X_validation.shape)
print (Y_validation.shape)
print("Data Rotation and Flipping Complete")
print (X_train.shape)
print (Y_train.shape)
print (X_validation.shape)
print (Y_validation.shape)
X_train = np.concatenate((X_train,X_validation),axis=0)
Y_train = np.concatenate((Y_train,Y_validation),axis=0)
np.savez_compressed(file='train.npz',X=X_train,Y=Y_train)
np.savez_compressed(file='test.npz',X=X_test)

# npz = np.load('G:/Kaggle_data/Kaggle_bowl/train.npz') 
# X_train2 = npz['X'] 
# Y_train2 = npz['Y']
# X_test2 = np.load('G:/Kaggle_data/Kaggle_bowl/test.npz')['X']

# Check if training data looks all right
# ix = random.randint(0, len(train_ids))
# imshow(X_train[ix])
# plt.show()
# imshow(np.squeeze(Y_train[ix]))
# plt.show()

# Define IoU metric
"""def mean_iou(y_true, y_pred):
    prec = []
    for t in np.arange(0.5, 1.0, 0.05):
        y_pred_ = tf.to_int32(y_pred > t)
        score, up_opt = tf.metrics.mean_iou(y_true, y_pred_, 2)
        K.get_session().run(tf.local_variables_initializer())
        with tf.control_dependencies([up_opt]):
            score = tf.identity(score)
        prec.append(score)
    return K.mean(K.stack(prec), axis=0)"""

def dice_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def dice_coef_loss(y_true, y_pred):
    return -dice_coef(y_true, y_pred)

# Build U-Net model
inputs = Input((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))
s = Lambda(lambda x: x / 255) (inputs)

c1 = Conv2D(16, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (s)
c1 = Dropout(0.1) (c1)
c1 = Conv2D(16, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c1)
p1 = MaxPooling2D((2, 2)) (c1)

c2 = Conv2D(32, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (p1)
c2 = Dropout(0.1) (c2)
c2 = Conv2D(32, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c2)
p2 = MaxPooling2D((2, 2)) (c2)

c3 = Conv2D(64, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (p2)
c3 = Dropout(0.2) (c3)
c3 = Conv2D(64, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c3)
p3 = MaxPooling2D((2, 2)) (c3)

c4 = Conv2D(128, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (p3)
c4 = Dropout(0.2) (c4)
c4 = Conv2D(128, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c4)
p4 = MaxPooling2D(pool_size=(2, 2)) (c4)

c5 = Conv2D(256, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (p4)
c5 = Dropout(0.3) (c5)
c5 = Conv2D(256, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c5)

u6 = Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same') (c5)
u6 = concatenate([u6, c4])
c6 = Conv2D(128, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (u6)
c6 = Dropout(0.2) (c6)
c6 = Conv2D(128, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c6)

u7 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same') (c6)
u7 = concatenate([u7, c3])
c7 = Conv2D(64, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (u7)
c7 = Dropout(0.2) (c7)
c7 = Conv2D(64, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c7)

u8 = Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same') (c7)
u8 = concatenate([u8, c2])
c8 = Conv2D(32, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (u8)
c8 = Dropout(0.1) (c8)
c8 = Conv2D(32, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c8)

u9 = Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same') (c8)
u9 = concatenate([u9, c1], axis=3)
c9 = Conv2D(16, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (u9)
c9 = Dropout(0.1) (c9)
c9 = Conv2D(16, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c9)

outputs = Conv2D(1, (1, 1), activation='sigmoid') (c9)

model = Model(inputs=[inputs], outputs=[outputs])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[dice_coef])
model.summary()

# Fit model
earlystopper = EarlyStopping(patience=5, verbose=1)
checkpointer = ModelCheckpoint('model-dsbowl2018-1_+img_rotated.h5', verbose=1, save_best_only=True)
results = model.fit(X_train, Y_train, validation_split=0.2, batch_size=16, epochs=50, 
                    callbacks=[earlystopper, checkpointer])
# results2 = model.fit(X_train2, Y_train2, validation_split=0.1, batch_size=16, epochs=50, 
#                     callbacks=[earlystopper, checkpointer])

# Predict on train, val and test
model = load_model('model-dsbowl2018-1_+img_rotated.h5', custom_objects={'dice_coef': dice_coef})
preds_train = model.predict(X_train[:int(X_train.shape[0]*0.9)], verbose=1)
preds_val = model.predict(X_train[int(X_train.shape[0]*0.9):], verbose=1)
preds_test = model.predict(X_test, verbose=1)

# preds_train2 = model.predict(X_train2[:int(X_train2.shape[0]*0.9)], verbose=1)
# preds_val2 = model.predict(X_train2[int(X_train2.shape[0]*0.9):], verbose=1)
# preds_test2 = model.predict(X_test2, verbose=1)

# Threshold predictions
preds_train_t = (preds_train > 0.5).astype(np.uint8)
preds_val_t = (preds_val > 0.5).astype(np.uint8)
preds_test_t = (preds_test > 0.5).astype(np.uint8)

# preds_train_t2 = (preds_train2 > 0.5).astype(np.uint8)
# preds_val_t2 = (preds_val2 > 0.5).astype(np.uint8)
# preds_test_t2 = (preds_test2 > 0.5).astype(np.uint8)

# Create list of upsampled test masks
preds_test_upsampled = []
for i in range(len(preds_test)):
    preds_test_upsampled.append(resize(np.squeeze(preds_test[i]), 
                                       (sizes_test[i][0], sizes_test[i][1]), 
                                       mode='constant', preserve_range=True))
# for i in range(len(preds_test2)):
#     preds_test_upsampled.append(resize(np.squeeze(preds_test2[i]), 
#                                        (sizes_test[i][0], sizes_test[i][1]), 
#                                        mode='constant', preserve_range=True))
    
# Perform a sanity check on some random training samples
# ix = random.randint(0, len(preds_train_t))
# imshow(X_train[ix])
# plt.show()
# imshow(np.squeeze(Y_train[ix]))
# plt.show()
# imshow(np.squeeze(preds_train_t[ix]))
# plt.show()

# Perform a sanity check on some random validation samples
# ix = random.randint(0, len(preds_val_t))
# imshow(X_train[int(X_train.shape[0]*0.9):][ix])
# plt.show()
# imshow(np.squeeze(Y_train[int(Y_train.shape[0]*0.9):][ix]))
# plt.show()
# imshow(np.squeeze(preds_val_t[ix]))
# plt.show()

# Run-length encoding stolen from https://www.kaggle.com/rakhlin/fast-run-length-encoding-python
def rle_encoding(x):
    dots = np.where(x.T.flatten() == 1)[0]
    run_lengths = []
    prev = -2
    for b in dots:
        if (b>prev+1): run_lengths.extend((b + 1, 0))
        run_lengths[-1] += 1
        prev = b
    return run_lengths

def prob_to_rles(x, cutoff=0.5):
    lab_img = label(x > cutoff)
    for i in range(1, lab_img.max() + 1):
        yield rle_encoding(lab_img == i)
        
new_test_ids = []
rles = []
for n, id_ in enumerate(test_ids):
    rle = list(prob_to_rles(preds_test_upsampled[n]))
    rles.extend(rle)
    new_test_ids.extend([id_] * len(rle))
    
# Create submission DataFrame

sub = pd.DataFrame()
sub['ImageId'] = new_test_ids
sub['EncodedPixels'] = pd.Series(rles).apply(lambda x: ' '.join(str(y) for y in x))
sub.to_csv('sub-dsbowl2018-1_%s_256_scale+flip_rotate.csv' % time, index=False)



Getting and resizing train images and masks ... 


100%|██████████| 670/670 [02:39<00:00,  4.20it/s]


Getting and resizing test images ... 


100%|██████████| 65/65 [00:01<00:00, 52.42it/s]


Done!
(670, 256, 256, 3)
(670, 256, 256, 1)
(65, 256, 256, 3)
Validation Set of Size 50 Separated
[[[[  2   2   2]
   [  2   2   2]
   [  3   3   3]
   ...
   [  4   4   4]
   [  4   4   4]
   [  4   4   4]]

  [[  2   2   2]
   [  3   3   3]
   [  4   4   4]
   ...
   [  5   5   5]
   [  5   5   5]
   [  5   5   5]]

  [[  2   2   2]
   [  3   3   3]
   [  4   4   4]
   ...
   [  5   5   5]
   [  5   5   5]
   [  5   5   5]]

  ...

  [[  2   2   2]
   [  2   2   2]
   [  2   2   2]
   ...
   [  3   3   3]
   [  3   3   3]
   [  2   2   2]]

  [[  2   2   2]
   [  2   2   2]
   [  2   2   2]
   ...
   [  3   3   3]
   [  2   2   2]
   [  2   2   2]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  2   2   2]
   [  1   1   1]
   [  2   2   2]]]


 [[[  3   3   3]
   [  3   3   3]
   [  3   3   3]
   ...
   [  4   4   4]
   [  4   4   4]
   [  4   4   4]]

  [[  3   3   3]
   [  4   4   4]
   [  4   4   4]
   ...
   [  4   4   4]
   [  4   4   4]
   [  4   4   4]]

  [[ 

   [ 14  14  14]]]]
(3100, 256, 256, 3)
(3100, 256, 256, 1)
(50, 256, 256, 3)
(50, 256, 256, 1)
Data Rotation and Flipping Complete
(3100, 256, 256, 3)
(3100, 256, 256, 1)
(50, 256, 256, 3)
(50, 256, 256, 1)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            (None, 256, 256, 3)  0                                            
__________________________________________________________________________________________________
lambda_7 (Lambda)               (None, 256, 256, 3)  0           input_7[0][0]                    
__________________________________________________________________________________________________
conv2d_97 (Conv2D)              (None, 256, 256, 16) 448         lambda_7[0][0]                   
__________________________________________________________________________________________________


concatenate_22 (Concatenate)    (None, 256, 256, 32) 0           conv2d_transpose_22[0][0]        
                                                                 conv2d_98[0][0]                  
__________________________________________________________________________________________________
conv2d_113 (Conv2D)             (None, 256, 256, 16) 4624        concatenate_22[0][0]             
__________________________________________________________________________________________________
dropout_55 (Dropout)            (None, 256, 256, 16) 0           conv2d_113[0][0]                 
__________________________________________________________________________________________________
conv2d_114 (Conv2D)             (None, 256, 256, 16) 2320        dropout_55[0][0]                 
__________________________________________________________________________________________________
conv2d_115 (Conv2D)             (None, 256, 256, 1)  17          conv2d_114[0][0]                 
Total para

2520/2520 [==============================] - ETA: 27:09 - loss: 0.6769 - dice_coef: 0.25 - ETA: 24:12 - loss: 0.6466 - dice_coef: 0.23 - ETA: 23:08 - loss: 0.6156 - dice_coef: 0.20 - ETA: 22:33 - loss: 0.6070 - dice_coef: 0.18 - ETA: 22:05 - loss: 0.6046 - dice_coef: 0.17 - ETA: 21:46 - loss: 0.5809 - dice_coef: 0.17 - ETA: 21:27 - loss: 0.5624 - dice_coef: 0.17 - ETA: 21:14 - loss: 0.5510 - dice_coef: 0.18 - ETA: 21:00 - loss: 0.5340 - dice_coef: 0.19 - ETA: 20:48 - loss: 0.5132 - dice_coef: 0.20 - ETA: 20:36 - loss: 0.4963 - dice_coef: 0.21 - ETA: 20:27 - loss: 0.4858 - dice_coef: 0.22 - ETA: 20:16 - loss: 0.4735 - dice_coef: 0.22 - ETA: 20:07 - loss: 0.4652 - dice_coef: 0.23 - ETA: 19:56 - loss: 0.4569 - dice_coef: 0.24 - ETA: 19:47 - loss: 0.4483 - dice_coef: 0.24 - ETA: 19:38 - loss: 0.4482 - dice_coef: 0.23 - ETA: 19:28 - loss: 0.4382 - dice_coef: 0.24 - ETA: 19:19 - loss: 0.4337 - dice_coef: 0.24 - ETA: 19:09 - loss: 0.4282 - dice_coef: 0.24 - ETA: 19:01 - loss: 0.4204 - dice_co

2520/2520 [==============================] - ETA: 21:11 - loss: 0.1143 - dice_coef: 0.79 - ETA: 21:17 - loss: 0.1167 - dice_coef: 0.74 - ETA: 21:06 - loss: 0.1283 - dice_coef: 0.72 - ETA: 21:02 - loss: 0.1381 - dice_coef: 0.71 - ETA: 20:51 - loss: 0.1301 - dice_coef: 0.73 - ETA: 20:46 - loss: 0.1288 - dice_coef: 0.73 - ETA: 20:36 - loss: 0.1227 - dice_coef: 0.74 - ETA: 20:29 - loss: 0.1247 - dice_coef: 0.74 - ETA: 20:21 - loss: 0.1268 - dice_coef: 0.73 - ETA: 20:13 - loss: 0.1222 - dice_coef: 0.74 - ETA: 20:05 - loss: 0.1242 - dice_coef: 0.74 - ETA: 19:57 - loss: 0.1231 - dice_coef: 0.74 - ETA: 19:49 - loss: 0.1221 - dice_coef: 0.74 - ETA: 19:44 - loss: 0.1198 - dice_coef: 0.75 - ETA: 19:40 - loss: 0.1197 - dice_coef: 0.75 - ETA: 19:31 - loss: 0.1170 - dice_coef: 0.75 - ETA: 19:23 - loss: 0.1165 - dice_coef: 0.75 - ETA: 19:14 - loss: 0.1156 - dice_coef: 0.75 - ETA: 19:06 - loss: 0.1162 - dice_coef: 0.76 - ETA: 18:58 - loss: 0.1148 - dice_coef: 0.76 - ETA: 18:50 - loss: 0.1126 - dice_co

2520/2520 [==============================] - ETA: 21:32 - loss: 0.1067 - dice_coef: 0.76 - ETA: 21:24 - loss: 0.0963 - dice_coef: 0.81 - ETA: 21:14 - loss: 0.1001 - dice_coef: 0.81 - ETA: 21:06 - loss: 0.0996 - dice_coef: 0.81 - ETA: 20:58 - loss: 0.0986 - dice_coef: 0.82 - ETA: 20:47 - loss: 0.0960 - dice_coef: 0.82 - ETA: 20:41 - loss: 0.0904 - dice_coef: 0.83 - ETA: 20:31 - loss: 0.0908 - dice_coef: 0.82 - ETA: 20:24 - loss: 0.0877 - dice_coef: 0.83 - ETA: 20:15 - loss: 0.0883 - dice_coef: 0.83 - ETA: 20:08 - loss: 0.0894 - dice_coef: 0.83 - ETA: 19:59 - loss: 0.0878 - dice_coef: 0.83 - ETA: 19:52 - loss: 0.0884 - dice_coef: 0.83 - ETA: 19:43 - loss: 0.0868 - dice_coef: 0.83 - ETA: 19:35 - loss: 0.0850 - dice_coef: 0.83 - ETA: 19:27 - loss: 0.0882 - dice_coef: 0.83 - ETA: 19:19 - loss: 0.0897 - dice_coef: 0.83 - ETA: 19:10 - loss: 0.0906 - dice_coef: 0.83 - ETA: 19:03 - loss: 0.0897 - dice_coef: 0.83 - ETA: 18:54 - loss: 0.0883 - dice_coef: 0.83 - ETA: 18:46 - loss: 0.0865 - dice_co

2520/2520 [==============================] - ETA: 21:22 - loss: 0.0794 - dice_coef: 0.84 - ETA: 21:21 - loss: 0.0658 - dice_coef: 0.87 - ETA: 21:11 - loss: 0.0673 - dice_coef: 0.86 - ETA: 21:04 - loss: 0.0679 - dice_coef: 0.85 - ETA: 20:57 - loss: 0.0667 - dice_coef: 0.86 - ETA: 20:48 - loss: 0.0721 - dice_coef: 0.84 - ETA: 20:40 - loss: 0.0746 - dice_coef: 0.83 - ETA: 20:31 - loss: 0.0739 - dice_coef: 0.83 - ETA: 20:24 - loss: 0.0748 - dice_coef: 0.83 - ETA: 20:15 - loss: 0.0752 - dice_coef: 0.83 - ETA: 20:08 - loss: 0.0775 - dice_coef: 0.83 - ETA: 19:59 - loss: 0.0790 - dice_coef: 0.83 - ETA: 19:52 - loss: 0.0793 - dice_coef: 0.83 - ETA: 19:43 - loss: 0.0798 - dice_coef: 0.83 - ETA: 19:35 - loss: 0.0790 - dice_coef: 0.83 - ETA: 19:26 - loss: 0.0800 - dice_coef: 0.83 - ETA: 19:18 - loss: 0.0832 - dice_coef: 0.83 - ETA: 19:09 - loss: 0.0822 - dice_coef: 0.83 - ETA: 19:02 - loss: 0.0812 - dice_coef: 0.83 - ETA: 18:53 - loss: 0.0806 - dice_coef: 0.83 - ETA: 18:45 - loss: 0.0839 - dice_co

2520/2520 [==============================] - ETA: 21:16 - loss: 0.1077 - dice_coef: 0.81 - ETA: 21:17 - loss: 0.1060 - dice_coef: 0.81 - ETA: 21:07 - loss: 0.0985 - dice_coef: 0.83 - ETA: 21:03 - loss: 0.0929 - dice_coef: 0.83 - ETA: 20:53 - loss: 0.0891 - dice_coef: 0.84 - ETA: 20:45 - loss: 0.0947 - dice_coef: 0.83 - ETA: 20:36 - loss: 0.0973 - dice_coef: 0.83 - ETA: 20:29 - loss: 0.0923 - dice_coef: 0.83 - ETA: 20:20 - loss: 0.0873 - dice_coef: 0.84 - ETA: 20:13 - loss: 0.0838 - dice_coef: 0.84 - ETA: 20:05 - loss: 0.0816 - dice_coef: 0.85 - ETA: 19:58 - loss: 0.0827 - dice_coef: 0.84 - ETA: 19:49 - loss: 0.0861 - dice_coef: 0.84 - ETA: 19:41 - loss: 0.0851 - dice_coef: 0.84 - ETA: 19:33 - loss: 0.0834 - dice_coef: 0.84 - ETA: 19:25 - loss: 0.0834 - dice_coef: 0.84 - ETA: 19:17 - loss: 0.0838 - dice_coef: 0.84 - ETA: 19:09 - loss: 0.0842 - dice_coef: 0.84 - ETA: 19:01 - loss: 0.0848 - dice_coef: 0.84 - ETA: 18:52 - loss: 0.0857 - dice_coef: 0.84 - ETA: 18:45 - loss: 0.0869 - dice_co

2520/2520 [==============================] - ETA: 21:18 - loss: 0.1077 - dice_coef: 0.85 - ETA: 21:20 - loss: 0.1073 - dice_coef: 0.83 - ETA: 21:11 - loss: 0.0966 - dice_coef: 0.83 - ETA: 21:06 - loss: 0.0872 - dice_coef: 0.84 - ETA: 20:57 - loss: 0.0871 - dice_coef: 0.84 - ETA: 20:52 - loss: 0.0837 - dice_coef: 0.84 - ETA: 20:41 - loss: 0.0799 - dice_coef: 0.84 - ETA: 20:35 - loss: 0.0773 - dice_coef: 0.85 - ETA: 20:26 - loss: 0.0782 - dice_coef: 0.85 - ETA: 20:18 - loss: 0.0797 - dice_coef: 0.84 - ETA: 20:08 - loss: 0.0772 - dice_coef: 0.85 - ETA: 20:00 - loss: 0.0758 - dice_coef: 0.85 - ETA: 19:51 - loss: 0.0744 - dice_coef: 0.85 - ETA: 19:44 - loss: 0.0745 - dice_coef: 0.85 - ETA: 19:35 - loss: 0.0759 - dice_coef: 0.85 - ETA: 19:27 - loss: 0.0762 - dice_coef: 0.85 - ETA: 19:18 - loss: 0.0755 - dice_coef: 0.85 - ETA: 19:10 - loss: 0.0753 - dice_coef: 0.85 - ETA: 19:01 - loss: 0.0752 - dice_coef: 0.85 - ETA: 18:53 - loss: 0.0752 - dice_coef: 0.85 - ETA: 18:44 - loss: 0.0769 - dice_co

2520/2520 [==============================] - ETA: 21:11 - loss: 0.0716 - dice_coef: 0.86 - ETA: 21:17 - loss: 0.0980 - dice_coef: 0.82 - ETA: 21:08 - loss: 0.0823 - dice_coef: 0.84 - ETA: 21:05 - loss: 0.0715 - dice_coef: 0.85 - ETA: 20:54 - loss: 0.0830 - dice_coef: 0.85 - ETA: 20:47 - loss: 0.0828 - dice_coef: 0.85 - ETA: 20:39 - loss: 0.0817 - dice_coef: 0.85 - ETA: 20:32 - loss: 0.0814 - dice_coef: 0.85 - ETA: 20:23 - loss: 0.0814 - dice_coef: 0.85 - ETA: 20:17 - loss: 0.0799 - dice_coef: 0.85 - ETA: 20:08 - loss: 0.0807 - dice_coef: 0.85 - ETA: 20:00 - loss: 0.0811 - dice_coef: 0.84 - ETA: 19:51 - loss: 0.0808 - dice_coef: 0.85 - ETA: 19:43 - loss: 0.0816 - dice_coef: 0.85 - ETA: 19:34 - loss: 0.0832 - dice_coef: 0.85 - ETA: 19:26 - loss: 0.0840 - dice_coef: 0.85 - ETA: 19:17 - loss: 0.0841 - dice_coef: 0.85 - ETA: 19:09 - loss: 0.0828 - dice_coef: 0.85 - ETA: 19:00 - loss: 0.0815 - dice_coef: 0.85 - ETA: 18:53 - loss: 0.0799 - dice_coef: 0.85 - ETA: 18:44 - loss: 0.0790 - dice_co

2520/2520 [==============================] - ETA: 21:36 - loss: 0.1091 - dice_coef: 0.84 - ETA: 21:17 - loss: 0.1165 - dice_coef: 0.83 - ETA: 21:12 - loss: 0.1015 - dice_coef: 0.85 - ETA: 21:03 - loss: 0.0974 - dice_coef: 0.85 - ETA: 20:54 - loss: 0.0998 - dice_coef: 0.85 - ETA: 20:46 - loss: 0.0923 - dice_coef: 0.85 - ETA: 20:37 - loss: 0.0877 - dice_coef: 0.84 - ETA: 20:31 - loss: 0.0842 - dice_coef: 0.85 - ETA: 20:24 - loss: 0.0815 - dice_coef: 0.85 - ETA: 20:17 - loss: 0.0792 - dice_coef: 0.85 - ETA: 20:07 - loss: 0.0793 - dice_coef: 0.85 - ETA: 20:00 - loss: 0.0795 - dice_coef: 0.85 - ETA: 19:50 - loss: 0.0776 - dice_coef: 0.85 - ETA: 19:43 - loss: 0.0809 - dice_coef: 0.85 - ETA: 19:34 - loss: 0.0804 - dice_coef: 0.85 - ETA: 19:26 - loss: 0.0790 - dice_coef: 0.85 - ETA: 19:17 - loss: 0.0786 - dice_coef: 0.85 - ETA: 19:09 - loss: 0.0778 - dice_coef: 0.85 - ETA: 19:01 - loss: 0.0765 - dice_coef: 0.86 - ETA: 18:53 - loss: 0.0774 - dice_coef: 0.85 - ETA: 18:44 - loss: 0.0771 - dice_co

2520/2520 [==============================] - ETA: 22:14 - loss: 0.0583 - dice_coef: 0.86 - ETA: 22:08 - loss: 0.0771 - dice_coef: 0.85 - ETA: 21:52 - loss: 0.0763 - dice_coef: 0.86 - ETA: 21:33 - loss: 0.0722 - dice_coef: 0.87 - ETA: 21:20 - loss: 0.0722 - dice_coef: 0.86 - ETA: 21:06 - loss: 0.0702 - dice_coef: 0.86 - ETA: 20:56 - loss: 0.0723 - dice_coef: 0.86 - ETA: 20:44 - loss: 0.0715 - dice_coef: 0.86 - ETA: 20:35 - loss: 0.0699 - dice_coef: 0.86 - ETA: 20:24 - loss: 0.0712 - dice_coef: 0.86 - ETA: 20:15 - loss: 0.0735 - dice_coef: 0.86 - ETA: 20:06 - loss: 0.0747 - dice_coef: 0.86 - ETA: 19:57 - loss: 0.0765 - dice_coef: 0.85 - ETA: 19:48 - loss: 0.0747 - dice_coef: 0.85 - ETA: 19:39 - loss: 0.0796 - dice_coef: 0.85 - ETA: 19:30 - loss: 0.0768 - dice_coef: 0.85 - ETA: 19:21 - loss: 0.0769 - dice_coef: 0.85 - ETA: 19:13 - loss: 0.0757 - dice_coef: 0.85 - ETA: 19:04 - loss: 0.0737 - dice_coef: 0.85 - ETA: 18:57 - loss: 0.0725 - dice_coef: 0.85 - ETA: 18:48 - loss: 0.0719 - dice_co

2520/2520 [==============================] - ETA: 21:39 - loss: 0.0686 - dice_coef: 0.88 - ETA: 21:21 - loss: 0.0723 - dice_coef: 0.84 - ETA: 21:17 - loss: 0.0758 - dice_coef: 0.84 - ETA: 21:03 - loss: 0.0715 - dice_coef: 0.85 - ETA: 20:57 - loss: 0.0769 - dice_coef: 0.85 - ETA: 20:47 - loss: 0.0804 - dice_coef: 0.85 - ETA: 20:40 - loss: 0.0769 - dice_coef: 0.85 - ETA: 20:30 - loss: 0.0752 - dice_coef: 0.85 - ETA: 20:23 - loss: 0.0730 - dice_coef: 0.86 - ETA: 20:14 - loss: 0.0743 - dice_coef: 0.85 - ETA: 20:05 - loss: 0.0718 - dice_coef: 0.86 - ETA: 19:57 - loss: 0.0707 - dice_coef: 0.86 - ETA: 19:49 - loss: 0.0699 - dice_coef: 0.86 - ETA: 19:41 - loss: 0.0714 - dice_coef: 0.86 - ETA: 19:33 - loss: 0.0724 - dice_coef: 0.86 - ETA: 19:25 - loss: 0.0709 - dice_coef: 0.86 - ETA: 19:17 - loss: 0.0704 - dice_coef: 0.86 - ETA: 19:08 - loss: 0.0722 - dice_coef: 0.85 - ETA: 19:00 - loss: 0.0723 - dice_coef: 0.85 - ETA: 18:51 - loss: 0.0729 - dice_coef: 0.85 - ETA: 18:43 - loss: 0.0738 - dice_co

2520/2520 [==============================] - ETA: 21:21 - loss: 0.0920 - dice_coef: 0.87 - ETA: 21:20 - loss: 0.0837 - dice_coef: 0.84 - ETA: 21:12 - loss: 0.0786 - dice_coef: 0.84 - ETA: 21:02 - loss: 0.0700 - dice_coef: 0.85 - ETA: 20:54 - loss: 0.0685 - dice_coef: 0.85 - ETA: 20:47 - loss: 0.0641 - dice_coef: 0.85 - ETA: 20:44 - loss: 0.0688 - dice_coef: 0.85 - ETA: 20:34 - loss: 0.0679 - dice_coef: 0.85 - ETA: 20:26 - loss: 0.0703 - dice_coef: 0.85 - ETA: 20:16 - loss: 0.0741 - dice_coef: 0.84 - ETA: 20:09 - loss: 0.0766 - dice_coef: 0.84 - ETA: 19:59 - loss: 0.0785 - dice_coef: 0.84 - ETA: 19:52 - loss: 0.0770 - dice_coef: 0.84 - ETA: 19:43 - loss: 0.0753 - dice_coef: 0.84 - ETA: 19:35 - loss: 0.0745 - dice_coef: 0.85 - ETA: 19:26 - loss: 0.0741 - dice_coef: 0.85 - ETA: 19:18 - loss: 0.0740 - dice_coef: 0.85 - ETA: 19:10 - loss: 0.0737 - dice_coef: 0.85 - ETA: 19:02 - loss: 0.0731 - dice_coef: 0.85 - ETA: 18:53 - loss: 0.0738 - dice_coef: 0.85 - ETA: 18:45 - loss: 0.0732 - dice_co

2520/2520 [==============================] - ETA: 21:18 - loss: 0.0899 - dice_coef: 0.84 - ETA: 21:18 - loss: 0.0749 - dice_coef: 0.85 - ETA: 21:09 - loss: 0.0674 - dice_coef: 0.86 - ETA: 21:05 - loss: 0.0696 - dice_coef: 0.86 - ETA: 20:54 - loss: 0.0684 - dice_coef: 0.86 - ETA: 20:47 - loss: 0.0667 - dice_coef: 0.86 - ETA: 20:37 - loss: 0.0700 - dice_coef: 0.85 - ETA: 20:30 - loss: 0.0720 - dice_coef: 0.85 - ETA: 20:21 - loss: 0.0760 - dice_coef: 0.85 - ETA: 20:13 - loss: 0.0753 - dice_coef: 0.85 - ETA: 20:05 - loss: 0.0739 - dice_coef: 0.85 - ETA: 19:56 - loss: 0.0744 - dice_coef: 0.85 - ETA: 19:49 - loss: 0.0741 - dice_coef: 0.85 - ETA: 19:40 - loss: 0.0733 - dice_coef: 0.85 - ETA: 19:33 - loss: 0.0744 - dice_coef: 0.85 - ETA: 19:24 - loss: 0.0732 - dice_coef: 0.85 - ETA: 19:16 - loss: 0.0722 - dice_coef: 0.85 - ETA: 19:08 - loss: 0.0739 - dice_coef: 0.85 - ETA: 19:01 - loss: 0.0738 - dice_coef: 0.85 - ETA: 18:52 - loss: 0.0735 - dice_coef: 0.85 - ETA: 18:45 - loss: 0.0731 - dice_co

2520/2520 [==============================] - ETA: 21:20 - loss: 0.0598 - dice_coef: 0.86 - ETA: 21:24 - loss: 0.0700 - dice_coef: 0.86 - ETA: 21:10 - loss: 0.0815 - dice_coef: 0.85 - ETA: 21:05 - loss: 0.0789 - dice_coef: 0.85 - ETA: 20:53 - loss: 0.0750 - dice_coef: 0.85 - ETA: 20:45 - loss: 0.0739 - dice_coef: 0.85 - ETA: 20:36 - loss: 0.0742 - dice_coef: 0.85 - ETA: 20:28 - loss: 0.0752 - dice_coef: 0.85 - ETA: 20:19 - loss: 0.0756 - dice_coef: 0.85 - ETA: 20:12 - loss: 0.0761 - dice_coef: 0.85 - ETA: 20:03 - loss: 0.0756 - dice_coef: 0.85 - ETA: 19:56 - loss: 0.0751 - dice_coef: 0.85 - ETA: 19:47 - loss: 0.0724 - dice_coef: 0.85 - ETA: 19:40 - loss: 0.0772 - dice_coef: 0.85 - ETA: 19:31 - loss: 0.0765 - dice_coef: 0.85 - ETA: 19:23 - loss: 0.0749 - dice_coef: 0.85 - ETA: 19:14 - loss: 0.0739 - dice_coef: 0.85 - ETA: 19:07 - loss: 0.0738 - dice_coef: 0.85 - ETA: 18:58 - loss: 0.0735 - dice_coef: 0.85 - ETA: 18:50 - loss: 0.0737 - dice_coef: 0.85 - ETA: 18:42 - loss: 0.0744 - dice_co

2520/2520 [==============================] - ETA: 21:15 - loss: 0.0465 - dice_coef: 0.90 - ETA: 21:19 - loss: 0.0576 - dice_coef: 0.89 - ETA: 21:07 - loss: 0.0507 - dice_coef: 0.90 - ETA: 21:08 - loss: 0.0597 - dice_coef: 0.88 - ETA: 20:55 - loss: 0.0577 - dice_coef: 0.89 - ETA: 20:48 - loss: 0.0604 - dice_coef: 0.88 - ETA: 20:39 - loss: 0.0592 - dice_coef: 0.89 - ETA: 20:31 - loss: 0.0618 - dice_coef: 0.88 - ETA: 20:23 - loss: 0.0606 - dice_coef: 0.88 - ETA: 20:14 - loss: 0.0612 - dice_coef: 0.88 - ETA: 20:07 - loss: 0.0656 - dice_coef: 0.87 - ETA: 19:58 - loss: 0.0665 - dice_coef: 0.87 - ETA: 19:51 - loss: 0.0677 - dice_coef: 0.87 - ETA: 19:43 - loss: 0.0670 - dice_coef: 0.87 - ETA: 19:35 - loss: 0.0673 - dice_coef: 0.87 - ETA: 19:26 - loss: 0.0664 - dice_coef: 0.87 - ETA: 19:19 - loss: 0.0675 - dice_coef: 0.87 - ETA: 19:09 - loss: 0.0666 - dice_coef: 0.87 - ETA: 19:02 - loss: 0.0653 - dice_coef: 0.87 - ETA: 18:53 - loss: 0.0657 - dice_coef: 0.87 - ETA: 18:49 - loss: 0.0663 - dice_co

2520/2520 [==============================] - ETA: 21:34 - loss: 0.0828 - dice_coef: 0.84 - ETA: 21:28 - loss: 0.0753 - dice_coef: 0.86 - ETA: 21:22 - loss: 0.0701 - dice_coef: 0.87 - ETA: 21:14 - loss: 0.0654 - dice_coef: 0.87 - ETA: 21:07 - loss: 0.0611 - dice_coef: 0.87 - ETA: 20:57 - loss: 0.0628 - dice_coef: 0.86 - ETA: 20:52 - loss: 0.0665 - dice_coef: 0.86 - ETA: 20:42 - loss: 0.0636 - dice_coef: 0.86 - ETA: 20:35 - loss: 0.0643 - dice_coef: 0.86 - ETA: 20:25 - loss: 0.0617 - dice_coef: 0.87 - ETA: 20:17 - loss: 0.0619 - dice_coef: 0.87 - ETA: 20:07 - loss: 0.0636 - dice_coef: 0.87 - ETA: 20:01 - loss: 0.0631 - dice_coef: 0.87 - ETA: 19:51 - loss: 0.0658 - dice_coef: 0.86 - ETA: 19:42 - loss: 0.0659 - dice_coef: 0.87 - ETA: 19:33 - loss: 0.0690 - dice_coef: 0.86 - ETA: 19:25 - loss: 0.0679 - dice_coef: 0.86 - ETA: 19:16 - loss: 0.0683 - dice_coef: 0.86 - ETA: 19:07 - loss: 0.0681 - dice_coef: 0.87 - ETA: 18:59 - loss: 0.0693 - dice_coef: 0.87 - ETA: 18:51 - loss: 0.0681 - dice_co

2520/2520 [==============================] - ETA: 21:44 - loss: 0.0508 - dice_coef: 0.87 - ETA: 21:27 - loss: 0.0587 - dice_coef: 0.86 - ETA: 21:23 - loss: 0.0687 - dice_coef: 0.86 - ETA: 21:11 - loss: 0.0683 - dice_coef: 0.86 - ETA: 21:06 - loss: 0.0663 - dice_coef: 0.86 - ETA: 20:54 - loss: 0.0706 - dice_coef: 0.86 - ETA: 20:47 - loss: 0.0670 - dice_coef: 0.87 - ETA: 20:37 - loss: 0.0674 - dice_coef: 0.87 - ETA: 20:29 - loss: 0.0677 - dice_coef: 0.87 - ETA: 20:19 - loss: 0.0656 - dice_coef: 0.87 - ETA: 20:11 - loss: 0.0637 - dice_coef: 0.87 - ETA: 20:02 - loss: 0.0640 - dice_coef: 0.87 - ETA: 19:55 - loss: 0.0636 - dice_coef: 0.87 - ETA: 19:46 - loss: 0.0646 - dice_coef: 0.87 - ETA: 19:39 - loss: 0.0649 - dice_coef: 0.87 - ETA: 19:30 - loss: 0.0633 - dice_coef: 0.87 - ETA: 19:22 - loss: 0.0642 - dice_coef: 0.87 - ETA: 19:14 - loss: 0.0652 - dice_coef: 0.87 - ETA: 19:05 - loss: 0.0641 - dice_coef: 0.87 - ETA: 18:57 - loss: 0.0629 - dice_coef: 0.87 - ETA: 18:49 - loss: 0.0632 - dice_co

2520/2520 [==============================] - ETA: 21:37 - loss: 0.0516 - dice_coef: 0.90 - ETA: 21:19 - loss: 0.0575 - dice_coef: 0.89 - ETA: 21:14 - loss: 0.0691 - dice_coef: 0.88 - ETA: 21:02 - loss: 0.0663 - dice_coef: 0.87 - ETA: 20:57 - loss: 0.0655 - dice_coef: 0.87 - ETA: 20:47 - loss: 0.0654 - dice_coef: 0.87 - ETA: 20:40 - loss: 0.0661 - dice_coef: 0.88 - ETA: 20:31 - loss: 0.0644 - dice_coef: 0.88 - ETA: 20:23 - loss: 0.0639 - dice_coef: 0.88 - ETA: 20:14 - loss: 0.0654 - dice_coef: 0.87 - ETA: 20:06 - loss: 0.0656 - dice_coef: 0.87 - ETA: 19:58 - loss: 0.0664 - dice_coef: 0.87 - ETA: 19:50 - loss: 0.0663 - dice_coef: 0.87 - ETA: 19:42 - loss: 0.0662 - dice_coef: 0.87 - ETA: 19:33 - loss: 0.0665 - dice_coef: 0.87 - ETA: 19:26 - loss: 0.0650 - dice_coef: 0.87 - ETA: 19:17 - loss: 0.0654 - dice_coef: 0.87 - ETA: 19:10 - loss: 0.0649 - dice_coef: 0.87 - ETA: 19:01 - loss: 0.0636 - dice_coef: 0.87 - ETA: 18:53 - loss: 0.0630 - dice_coef: 0.88 - ETA: 18:44 - loss: 0.0621 - dice_co

2520/2520 [==============================] - ETA: 21:30 - loss: 0.0631 - dice_coef: 0.87 - ETA: 21:18 - loss: 0.0633 - dice_coef: 0.87 - ETA: 21:11 - loss: 0.0614 - dice_coef: 0.87 - ETA: 21:01 - loss: 0.0608 - dice_coef: 0.87 - ETA: 20:55 - loss: 0.0612 - dice_coef: 0.87 - ETA: 20:45 - loss: 0.0595 - dice_coef: 0.88 - ETA: 20:38 - loss: 0.0639 - dice_coef: 0.87 - ETA: 20:29 - loss: 0.0645 - dice_coef: 0.87 - ETA: 20:21 - loss: 0.0621 - dice_coef: 0.87 - ETA: 20:13 - loss: 0.0645 - dice_coef: 0.87 - ETA: 20:05 - loss: 0.0635 - dice_coef: 0.88 - ETA: 19:56 - loss: 0.0626 - dice_coef: 0.88 - ETA: 19:49 - loss: 0.0619 - dice_coef: 0.88 - ETA: 19:40 - loss: 0.0624 - dice_coef: 0.88 - ETA: 19:32 - loss: 0.0617 - dice_coef: 0.88 - ETA: 19:24 - loss: 0.0627 - dice_coef: 0.88 - ETA: 19:15 - loss: 0.0623 - dice_coef: 0.88 - ETA: 19:08 - loss: 0.0622 - dice_coef: 0.88 - ETA: 18:59 - loss: 0.0617 - dice_coef: 0.88 - ETA: 18:51 - loss: 0.0611 - dice_coef: 0.88 - ETA: 18:43 - loss: 0.0610 - dice_co

2520/2520 [==============================] - ETA: 21:46 - loss: 0.0415 - dice_coef: 0.90 - ETA: 21:20 - loss: 0.0582 - dice_coef: 0.88 - ETA: 21:18 - loss: 0.0598 - dice_coef: 0.88 - ETA: 21:08 - loss: 0.0627 - dice_coef: 0.88 - ETA: 21:00 - loss: 0.0647 - dice_coef: 0.87 - ETA: 20:49 - loss: 0.0689 - dice_coef: 0.87 - ETA: 20:41 - loss: 0.0669 - dice_coef: 0.87 - ETA: 20:32 - loss: 0.0640 - dice_coef: 0.87 - ETA: 20:24 - loss: 0.0632 - dice_coef: 0.87 - ETA: 20:16 - loss: 0.0639 - dice_coef: 0.87 - ETA: 20:09 - loss: 0.0645 - dice_coef: 0.87 - ETA: 20:00 - loss: 0.0653 - dice_coef: 0.87 - ETA: 19:52 - loss: 0.0659 - dice_coef: 0.87 - ETA: 19:43 - loss: 0.0650 - dice_coef: 0.87 - ETA: 19:35 - loss: 0.0630 - dice_coef: 0.87 - ETA: 19:27 - loss: 0.0632 - dice_coef: 0.87 - ETA: 19:18 - loss: 0.0629 - dice_coef: 0.87 - ETA: 19:10 - loss: 0.0631 - dice_coef: 0.87 - ETA: 19:02 - loss: 0.0656 - dice_coef: 0.87 - ETA: 18:54 - loss: 0.0652 - dice_coef: 0.87 - ETA: 18:45 - loss: 0.0685 - dice_co

2520/2520 [==============================] - ETA: 21:35 - loss: 0.0643 - dice_coef: 0.88 - ETA: 21:15 - loss: 0.0716 - dice_coef: 0.88 - ETA: 21:12 - loss: 0.0665 - dice_coef: 0.87 - ETA: 21:00 - loss: 0.0655 - dice_coef: 0.87 - ETA: 20:54 - loss: 0.0641 - dice_coef: 0.87 - ETA: 20:43 - loss: 0.0651 - dice_coef: 0.86 - ETA: 20:36 - loss: 0.0623 - dice_coef: 0.86 - ETA: 20:28 - loss: 0.0614 - dice_coef: 0.87 - ETA: 20:20 - loss: 0.0628 - dice_coef: 0.87 - ETA: 20:11 - loss: 0.0611 - dice_coef: 0.87 - ETA: 20:04 - loss: 0.0605 - dice_coef: 0.87 - ETA: 19:55 - loss: 0.0596 - dice_coef: 0.87 - ETA: 19:47 - loss: 0.0603 - dice_coef: 0.87 - ETA: 19:39 - loss: 0.0589 - dice_coef: 0.87 - ETA: 19:32 - loss: 0.0594 - dice_coef: 0.87 - ETA: 19:23 - loss: 0.0619 - dice_coef: 0.87 - ETA: 19:15 - loss: 0.0624 - dice_coef: 0.87 - ETA: 19:07 - loss: 0.0631 - dice_coef: 0.87 - ETA: 18:59 - loss: 0.0629 - dice_coef: 0.87 - ETA: 18:51 - loss: 0.0618 - dice_coef: 0.87 - ETA: 18:44 - loss: 0.0606 - dice_co

2520/2520 [==============================] - ETA: 21:50 - loss: 0.0742 - dice_coef: 0.87 - ETA: 21:29 - loss: 0.0625 - dice_coef: 0.87 - ETA: 21:20 - loss: 0.0731 - dice_coef: 0.87 - ETA: 21:07 - loss: 0.0677 - dice_coef: 0.88 - ETA: 21:01 - loss: 0.0647 - dice_coef: 0.88 - ETA: 20:51 - loss: 0.0717 - dice_coef: 0.87 - ETA: 20:43 - loss: 0.0720 - dice_coef: 0.87 - ETA: 20:34 - loss: 0.0716 - dice_coef: 0.87 - ETA: 20:26 - loss: 0.0694 - dice_coef: 0.87 - ETA: 20:16 - loss: 0.0692 - dice_coef: 0.87 - ETA: 20:09 - loss: 0.0666 - dice_coef: 0.87 - ETA: 20:00 - loss: 0.0673 - dice_coef: 0.86 - ETA: 19:52 - loss: 0.0674 - dice_coef: 0.86 - ETA: 19:43 - loss: 0.0660 - dice_coef: 0.86 - ETA: 19:36 - loss: 0.0646 - dice_coef: 0.86 - ETA: 19:28 - loss: 0.0660 - dice_coef: 0.86 - ETA: 19:20 - loss: 0.0641 - dice_coef: 0.87 - ETA: 19:12 - loss: 0.0635 - dice_coef: 0.87 - ETA: 19:03 - loss: 0.0634 - dice_coef: 0.87 - ETA: 18:55 - loss: 0.0625 - dice_coef: 0.87 - ETA: 18:47 - loss: 0.0619 - dice_co

2520/2520 [==============================] - ETA: 21:49 - loss: 0.0736 - dice_coef: 0.86 - ETA: 21:23 - loss: 0.0574 - dice_coef: 0.88 - ETA: 21:16 - loss: 0.0615 - dice_coef: 0.88 - ETA: 21:03 - loss: 0.0624 - dice_coef: 0.88 - ETA: 20:56 - loss: 0.0558 - dice_coef: 0.88 - ETA: 20:45 - loss: 0.0549 - dice_coef: 0.88 - ETA: 20:39 - loss: 0.0529 - dice_coef: 0.88 - ETA: 20:30 - loss: 0.0521 - dice_coef: 0.88 - ETA: 20:23 - loss: 0.0539 - dice_coef: 0.88 - ETA: 20:13 - loss: 0.0537 - dice_coef: 0.88 - ETA: 20:07 - loss: 0.0543 - dice_coef: 0.88 - ETA: 19:57 - loss: 0.0563 - dice_coef: 0.88 - ETA: 19:50 - loss: 0.0572 - dice_coef: 0.88 - ETA: 19:42 - loss: 0.0568 - dice_coef: 0.88 - ETA: 19:34 - loss: 0.0576 - dice_coef: 0.88 - ETA: 19:25 - loss: 0.0575 - dice_coef: 0.88 - ETA: 19:17 - loss: 0.0585 - dice_coef: 0.88 - ETA: 19:09 - loss: 0.0588 - dice_coef: 0.88 - ETA: 19:01 - loss: 0.0586 - dice_coef: 0.88 - ETA: 18:53 - loss: 0.0592 - dice_coef: 0.88 - ETA: 18:44 - loss: 0.0600 - dice_co

2520/2520 [==============================] - ETA: 21:53 - loss: 0.0515 - dice_coef: 0.86 - ETA: 21:29 - loss: 0.0575 - dice_coef: 0.87 - ETA: 21:23 - loss: 0.0576 - dice_coef: 0.88 - ETA: 21:09 - loss: 0.0496 - dice_coef: 0.89 - ETA: 21:03 - loss: 0.0513 - dice_coef: 0.89 - ETA: 20:52 - loss: 0.0547 - dice_coef: 0.88 - ETA: 20:44 - loss: 0.0530 - dice_coef: 0.88 - ETA: 20:34 - loss: 0.0531 - dice_coef: 0.88 - ETA: 20:26 - loss: 0.0596 - dice_coef: 0.88 - ETA: 20:17 - loss: 0.0588 - dice_coef: 0.88 - ETA: 20:09 - loss: 0.0596 - dice_coef: 0.87 - ETA: 20:00 - loss: 0.0625 - dice_coef: 0.87 - ETA: 19:52 - loss: 0.0613 - dice_coef: 0.87 - ETA: 19:43 - loss: 0.0621 - dice_coef: 0.87 - ETA: 19:35 - loss: 0.0614 - dice_coef: 0.87 - ETA: 19:26 - loss: 0.0613 - dice_coef: 0.87 - ETA: 19:18 - loss: 0.0617 - dice_coef: 0.87 - ETA: 19:11 - loss: 0.0611 - dice_coef: 0.87 - ETA: 19:03 - loss: 0.0619 - dice_coef: 0.87 - ETA: 18:55 - loss: 0.0609 - dice_coef: 0.87 - ETA: 18:47 - loss: 0.0618 - dice_co

2520/2520 [==============================] - ETA: 21:34 - loss: 0.0604 - dice_coef: 0.90 - ETA: 21:19 - loss: 0.0713 - dice_coef: 0.88 - ETA: 21:16 - loss: 0.0670 - dice_coef: 0.89 - ETA: 21:04 - loss: 0.0600 - dice_coef: 0.89 - ETA: 20:58 - loss: 0.0650 - dice_coef: 0.89 - ETA: 20:48 - loss: 0.0633 - dice_coef: 0.89 - ETA: 20:41 - loss: 0.0602 - dice_coef: 0.89 - ETA: 20:32 - loss: 0.0598 - dice_coef: 0.89 - ETA: 20:25 - loss: 0.0632 - dice_coef: 0.89 - ETA: 20:16 - loss: 0.0635 - dice_coef: 0.89 - ETA: 20:08 - loss: 0.0621 - dice_coef: 0.89 - ETA: 20:00 - loss: 0.0616 - dice_coef: 0.89 - ETA: 19:53 - loss: 0.0607 - dice_coef: 0.89 - ETA: 19:45 - loss: 0.0607 - dice_coef: 0.89 - ETA: 19:36 - loss: 0.0593 - dice_coef: 0.89 - ETA: 19:29 - loss: 0.0590 - dice_coef: 0.89 - ETA: 19:21 - loss: 0.0586 - dice_coef: 0.89 - ETA: 19:13 - loss: 0.0585 - dice_coef: 0.89 - ETA: 19:04 - loss: 0.0579 - dice_coef: 0.89 - ETA: 18:57 - loss: 0.0571 - dice_coef: 0.89 - ETA: 18:48 - loss: 0.0599 - dice_co

2520/2520 [==============================] - ETA: 21:30 - loss: 0.0342 - dice_coef: 0.91 - ETA: 21:30 - loss: 0.0414 - dice_coef: 0.89 - ETA: 21:22 - loss: 0.0388 - dice_coef: 0.90 - ETA: 21:13 - loss: 0.0362 - dice_coef: 0.91 - ETA: 21:02 - loss: 0.0441 - dice_coef: 0.90 - ETA: 20:53 - loss: 0.0457 - dice_coef: 0.90 - ETA: 20:46 - loss: 0.0478 - dice_coef: 0.90 - ETA: 20:37 - loss: 0.0483 - dice_coef: 0.90 - ETA: 20:31 - loss: 0.0503 - dice_coef: 0.90 - ETA: 20:22 - loss: 0.0518 - dice_coef: 0.89 - ETA: 20:16 - loss: 0.0520 - dice_coef: 0.89 - ETA: 20:06 - loss: 0.0528 - dice_coef: 0.89 - ETA: 19:59 - loss: 0.0542 - dice_coef: 0.89 - ETA: 19:50 - loss: 0.0587 - dice_coef: 0.89 - ETA: 19:43 - loss: 0.0585 - dice_coef: 0.89 - ETA: 19:34 - loss: 0.0589 - dice_coef: 0.88 - ETA: 19:27 - loss: 0.0580 - dice_coef: 0.89 - ETA: 19:18 - loss: 0.0577 - dice_coef: 0.89 - ETA: 19:11 - loss: 0.0571 - dice_coef: 0.89 - ETA: 19:02 - loss: 0.0562 - dice_coef: 0.89 - ETA: 18:54 - loss: 0.0558 - dice_co

2520/2520 [==============================] - ETA: 21:43 - loss: 0.0770 - dice_coef: 0.85 - ETA: 21:23 - loss: 0.0634 - dice_coef: 0.84 - ETA: 21:19 - loss: 0.0728 - dice_coef: 0.84 - ETA: 21:08 - loss: 0.0751 - dice_coef: 0.83 - ETA: 21:05 - loss: 0.0753 - dice_coef: 0.84 - ETA: 20:54 - loss: 0.0717 - dice_coef: 0.84 - ETA: 20:48 - loss: 0.0794 - dice_coef: 0.84 - ETA: 20:38 - loss: 0.0786 - dice_coef: 0.84 - ETA: 20:31 - loss: 0.0771 - dice_coef: 0.84 - ETA: 20:22 - loss: 0.0757 - dice_coef: 0.85 - ETA: 20:14 - loss: 0.0756 - dice_coef: 0.85 - ETA: 20:05 - loss: 0.0760 - dice_coef: 0.84 - ETA: 19:57 - loss: 0.0731 - dice_coef: 0.85 - ETA: 19:49 - loss: 0.0734 - dice_coef: 0.85 - ETA: 19:41 - loss: 0.0737 - dice_coef: 0.85 - ETA: 19:32 - loss: 0.0745 - dice_coef: 0.85 - ETA: 19:24 - loss: 0.0742 - dice_coef: 0.85 - ETA: 19:15 - loss: 0.0736 - dice_coef: 0.85 - ETA: 19:07 - loss: 0.0724 - dice_coef: 0.85 - ETA: 18:58 - loss: 0.0715 - dice_coef: 0.86 - ETA: 18:50 - loss: 0.0724 - dice_co

2520/2520 [==============================] - ETA: 21:44 - loss: 0.0593 - dice_coef: 0.88 - ETA: 21:23 - loss: 0.0585 - dice_coef: 0.88 - ETA: 21:18 - loss: 0.0531 - dice_coef: 0.89 - ETA: 21:08 - loss: 0.0500 - dice_coef: 0.89 - ETA: 21:00 - loss: 0.0483 - dice_coef: 0.89 - ETA: 20:52 - loss: 0.0543 - dice_coef: 0.89 - ETA: 20:43 - loss: 0.0520 - dice_coef: 0.89 - ETA: 20:36 - loss: 0.0562 - dice_coef: 0.89 - ETA: 20:27 - loss: 0.0557 - dice_coef: 0.88 - ETA: 20:20 - loss: 0.0556 - dice_coef: 0.88 - ETA: 20:10 - loss: 0.0574 - dice_coef: 0.88 - ETA: 20:04 - loss: 0.0584 - dice_coef: 0.88 - ETA: 19:54 - loss: 0.0572 - dice_coef: 0.88 - ETA: 19:47 - loss: 0.0564 - dice_coef: 0.88 - ETA: 19:38 - loss: 0.0555 - dice_coef: 0.88 - ETA: 19:31 - loss: 0.0556 - dice_coef: 0.88 - ETA: 19:22 - loss: 0.0551 - dice_coef: 0.88 - ETA: 19:14 - loss: 0.0549 - dice_coef: 0.88 - ETA: 19:05 - loss: 0.0550 - dice_coef: 0.88 - ETA: 18:57 - loss: 0.0548 - dice_coef: 0.88 - ETA: 18:48 - loss: 0.0554 - dice_co

2520/2520 [==============================] - ETA: 21:31 - loss: 0.0500 - dice_coef: 0.87 - ETA: 21:34 - loss: 0.0742 - dice_coef: 0.86 - ETA: 21:19 - loss: 0.0633 - dice_coef: 0.87 - ETA: 21:14 - loss: 0.0654 - dice_coef: 0.87 - ETA: 21:01 - loss: 0.0595 - dice_coef: 0.87 - ETA: 20:55 - loss: 0.0580 - dice_coef: 0.87 - ETA: 20:44 - loss: 0.0551 - dice_coef: 0.88 - ETA: 20:37 - loss: 0.0546 - dice_coef: 0.88 - ETA: 20:27 - loss: 0.0551 - dice_coef: 0.88 - ETA: 20:20 - loss: 0.0581 - dice_coef: 0.88 - ETA: 20:11 - loss: 0.0587 - dice_coef: 0.88 - ETA: 20:03 - loss: 0.0566 - dice_coef: 0.88 - ETA: 19:54 - loss: 0.0568 - dice_coef: 0.88 - ETA: 19:46 - loss: 0.0567 - dice_coef: 0.88 - ETA: 19:37 - loss: 0.0568 - dice_coef: 0.88 - ETA: 19:30 - loss: 0.0565 - dice_coef: 0.88 - ETA: 19:20 - loss: 0.0568 - dice_coef: 0.88 - ETA: 19:12 - loss: 0.0568 - dice_coef: 0.88 - ETA: 19:04 - loss: 0.0562 - dice_coef: 0.88 - ETA: 18:55 - loss: 0.0554 - dice_coef: 0.89 - ETA: 18:47 - loss: 0.0552 - dice_co

65/65 [==============================] - ETA:  - ETA:  - 11s 173ms/step


65/65 [==============================] - ETA:  - ETA:  - 11s 169ms/step
